apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: prometheus-rollouts-demo
spec:
  replicas: 5
  strategy:
    canary:
      analysis:
        templates:
        - templateName: success-rate
        args:
        - name: service-name
          value: prometheus-rollouts-demo
      canaryService: prometheus-rollouts-demo-canary
      stableService: prometheus-rollouts-demo
      trafficRouting:
        nginx:
          stableIngress: prometheus-rollouts-demo
      steps:
      - setWeight: 10
      - pause: {duration: 10m}
      - setWeight: 20
      - pause: {duration: 10m}
      - setWeight: 50
      - pause: {duration: 10m}
      - setWeight: 80
      - pause: {duration: 10m}
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: prometheus-rollouts-demo
  template:
    metadata:
      labels:
        app: prometheus-rollouts-demo
    spec:
      containers:
      - name: prometheus-rollouts-demo
        image: argoproj/rollouts-demo:blue
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        resources:
          requests:
            memory: 32Mi
            cpu: 5m